project:
  type: book

book: 
  chapters:
    - index.qmd
    - preface.qmd
    - introduction.qmd
    - interventions.qmd
    - tests.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

csl: vancouver-brackets.csl

format:
  html:
    theme: cosmo
    css: nocopy.css
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png  

editor: visual

copyright: "© 2025 Ashraf Nabhan. All rights reserved."

