project:
  type: book

book:
  title: "An Introduction to Evidence Synthesis"
  chapters:
    - index.qmd
    - preface.qmd
    - introduction.qmd
    - part: "Healthcare interventions"
      chapters: 
        - protocol.qmd
        - review.qmd
    - part: "Clinical tests"
      chapters: 
        - tests.qmd
    - summary.qmd
    - ref.qmd

bibliography: references.bib

csl: vancouver-brackets.csl

format:
  html:
    theme: cosmo
    css: nocopy.css
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png  

editor: visual

copyright: "© 2025 Ashraf Nabhan. All rights reserved."

