project:
  type: book
  output-dir: docs

toc-title: "On this page"
toc: true
book:
  title: "Evidence Synthesis"
  subtitle: "Finding what works in healthcare"
  url: https://www.ecebm.com
  date: today
  author:
  - name: "Prof. Ashraf Nabhan"
    affiliations:
      - "Faculty of Medicine, Ain Shams University"
      - "Head of Clinical Research Unit, Faculty of Medicine, MTI University"
    email: "anabhan@med.asu.edu.eg" 
    orcid: "0000-0003-4572-2210"
  sharing: [twitter, facebook]
  description: |
    Intended for students, researchers, and practitioners, 
    this book aims to strengthen readers’ capacity to conduct and critically appraise systematic reviews, 
    thereby advancing evidence-based practice and research integrity.
  keyword: Systematic reviews, Meta-analysis, Evidence Synthesis, Knowledge translation
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Reviews of Healthcare Interventions"
      chapters:
        - protocol.qmd
        - review.qmd
    - part: "Reviews of Clinical Tests"
      chapters:
        - tests.qmd
    - ref.qmd

bibliography: references.bib
csl: vancouver-author-date.csl

format:
  html:
    theme: cosmo
    fontsize: 1.2em
    linestretch: 1.5
    mainfont: Helvetica Neue, Helvetica, Arial, sans
    monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    code-link: true  
    css: nocopy.css
    theme-toggle: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    fontsize: 10pt
    papersize: a4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
  epub:
    cover-image: cover.png  

editor: visual

copyright: "© 2025 Ashraf Nabhan. All rights reserved"

